name: Build and push wulpix docker image to DockerHub

on:
  push:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get short commit SHA
      id: git_sha
      run: echo "name=sha::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    # - name: Build Docker image
    #   id: docker_build
    #   run: docker build . --file Dockerfile --tag asheranilkurian/wulpix:v${{ steps.git_sha.outputs.sha }}
    # - name: Push Docker image to Docker Hub
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push asheranilkurian/wulpix:v${{ steps.git_sha.outputs.sha }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: asheranilkurian/wulpix:v${{ steps.git_sha.outputs.sha }}
